# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch: null
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: Setup git
        run: |
          git switch main
          git config --global user.name "Közlöny Updater"
          git config --global user.email "kozlonyupdater@github.com"
          git remote set-url --push origin https://d3n972:${GITHUB_TOKEN}@github.com/OpenDataHU/kozlonyok.git
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: execute py script # run file
        run: |
          python app.py
           git add data/*
           git commit --allow-empty -m "Update"
           git push
